version: '3'
services:
  llm-demo:
    image: llm-demo
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      VIRTUAL_PORT: 3000 # tells our nginx proxy what port your app is listening on
      VIRTUAL_HOST: llm-demo.dev.tk.sg # how to find your app from outside
      CERT_NAME: _.dev.tk.sg

    networks:
      devtksg: # same network that our reverse proxy is on
    restart: always

networks:
  devtksg:
    external: true

